[project]
name = "selenium-pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings>=2.10.1",
    "pytest>=8.4.1",
    "selenium>=4.34.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.8",
]
