name: web test lab CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: get changes
        run: | 
          chmod +x .github/scripts/*
          .github/scripts/list-changes.sh

      - name: run tests
        if: ${{ steps.list-changes.outputs.changes != '' }}
        run: |
          echo "Changes detected: ${{ steps.list-changes.outputs.changes }}"
